### ISSUE TITLE
bwa mem -K hidden option reference?

### ISSUE THREAD

**Issue by ryanrichholt** [apregier/pipeline-sync#2]
Regarding this line:

`Use -K 100000000 to achieve deterministic alignment results (Note: this is a hidden option)`

Can you explain which randomness this hidden option eliminates? As far as I know, the alignments are deterministic given identical inputs, but batching or reordering of the reads would cause changes in output. Here is a description of the randomness: https://www.biostars.org/p/238628/#238817

**Comment by liuxf09** [comment]
bwa processes reads by chunks, while the default chunk size is `threads * 10M` bases. This chunk size may affect the bwa results: in bwa, it needs compute the insert size distribution per chunk after initial alignment, which is used in the later algorithm to choose the best alignment. Unless this chunk size is fixed using `-K` option, it may change with the number of threads, hence not deterministic result.
